### ISSUE TITLE
colour yellow is not accepted, red is chosen instead

### ISSUE THREAD

**Issue by misvae** [demonnic/Highlighter#4]
When adding a new highlight category using the following command

`hl cat add mob_important#bold = true, fg = yellow`

the resulting category will highlight as bold and red:

<pre>
(Highlighter): Configuration and highlight items for category mob_important
(Highlighter): bold     : true
(Highlighter): italics  : false
(Highlighter): underline: false
(Highlighter): paused   : false
(Highlighter): fg       : red
(Highlighter): bg       : false
(Highlighter): Items:
  seahorse, Seahorse
</pre>

**Comment by demonnic** [comment]
the quotes are still required and I haven't thought of a good way around that as yet short of searching for items token by token in the string.. which I may end up doing to add some resiliency but haven't decided as yet. 

Next version will have the default fg set to false though.

**Comment by demonnic** [comment]
changed in 1.3.0
